# This is a simplified config where the rest of the
# settings are omitted and will be set by default.
# See config.yml for the full configuration options.
config:
  bind: 0.0.0.0:25565
  servers:
    server-0: server-0.servers:25565
    server-1: server-1.servers:25565
  try:
    - server-0
    - server-1
