version: 2
before:
  hooks:
    - go mod download
    - make wasm-native-lib
builds:
  - id: gate
    env: [ CGO_ENABLED=1 ]
    tags:
      - wasm_native
    ldflags:
      - "-s -w"
      - "-X 'go.minekube.com/gate/pkg/version.Version={{.Version}}'"
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: gate
    ids:
      - gate
    formats:
      - binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
release:
  mode: keep-existing
  replace_existing_artifacts: true
