version: 2
before:
  hooks:
    - go mod download
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X go.minekube.com/gate/pkg/telemetry.Version={{.Version}}
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
