version: 2
before:
  hooks:
    - go mod download
builds:
  - id: gate
    env: [ CGO_ENABLED=0 ]
    ldflags:
      - "-s -w"
      - "-X 'go.minekube.com/gate/pkg/version.Version={{.Version}}'"
    goos:
      - linux
      - windows
      - darwin
  - id: gate-musl
    env: [ CGO_ENABLED=0 ]
    tags:
      - musl
    ldflags:
      - "-s -w"
      - "-X 'go.minekube.com/gate/pkg/version.Version={{.Version}}'"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - '386'
archives:
  - id: gate
    ids:
      - gate
    formats:
      - binary
  - id: gate-musl
    ids:
      - gate-musl
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}_musl"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
release:
  mode: keep-existing
  replace_existing_artifacts: true
