# This is a simplified config where the rest of the
# settings are omitted and will be set by default.
# See config.yml for the full configuration options.
#
# The Minecraft editions Gate supports.
editions:
  # Java Minecraft edition is the first popular edition for desktops.
  java:
    enabled: true
    config:
      bind: 0.0.0.0:25565
      servers:
        server1: localhost:25566
      try:
        - server1

connect:
  # Enabling Connect makes Gate register itself to Connect network.
  enabled: false
  services:
    addr: localhost:8443
    watch:
      enabled: true
    tunnel:
      enabled: true
