config:
  bind: 0.0.0.0:25565
  onlineMode: true
  servers:
    server1: 0.0.0.0:25566
  try:
    - server1
  # forwarding:
    # mode: legacy
    # velocitySecret: 'bedrock-crossplay-secret'
  status:
    motd: |
      §bGate + Geyser Cross-Play
      §eJava & Bedrock Players Welcome!

# Enable Bedrock edition support
editions:
  java:
    enabled: true
  bedrock:
    enabled: true
    config:
      # Geyser will connect to this address
      geyserListenAddr: '0.0.0.0:25567'
      # Username format for Bedrock players to avoid conflicts
      usernameFormat: '.%s'
      # Path to Floodgate key for authentication
      floodgateKeyPath: '.examples/bedrock/geyser/key.pem'
