# This is a simplified config where the rest of the
# settings are omitted and will be set by default.
# See config.yml for the full configuration options.
config:
  bind: 0.0.0.0:25565
  servers:
    server1: localhost:25566
    server2: localhost:25567
  try:
    - server1
    - server2

editions:
  java:
    enabled: true
  bedrock:
    enabled: true
    # Geyser will connect to this address
    geyserListenAddr: "0.0.0.0:25567"
    # Username format for Bedrock players to avoid conflicts
    usernameFormat: ".%s"
    # Path to Floodgate key for authentication
    floodgateKeyPath: "./floodgate.pem"