// Code generated by gate-wasm-gen; DO NOT EDIT.

package api

import (
	"context"

	"go.minekube.com/gate/internal/wasm/runtime/dispatch"
)

type GeneratedCallbackDescriptor struct {
	ID              uint32
	Identity        string
	WITName         string
	CallOperationID uint32
}

var GeneratedCallbacks = [...]GeneratedCallbackDescriptor{
	{
		ID:              1,
		Identity:        "callback-0105467f2bef",
		WITName:         "callback-0105467f2bef",
		CallOperationID: 2147483649,
	},
	{
		ID:              2,
		Identity:        "callback-1178afb46377",
		WITName:         "callback-1178afb46377",
		CallOperationID: 2147483650,
	},
	{
		ID:              3,
		Identity:        "callback-1f86eef915ce",
		WITName:         "callback-1f86eef915ce",
		CallOperationID: 2147483651,
	},
	{
		ID:              4,
		Identity:        "callback-2053c44117ea",
		WITName:         "callback-2053c44117ea",
		CallOperationID: 2147483652,
	},
	{
		ID:              5,
		Identity:        "callback-2c1c5989286b",
		WITName:         "callback-2c1c5989286b",
		CallOperationID: 2147483653,
	},
	{
		ID:              6,
		Identity:        "callback-4e5db8a68395",
		WITName:         "callback-4e5db8a68395",
		CallOperationID: 2147483654,
	},
	{
		ID:              7,
		Identity:        "callback-8ce8588e75ea",
		WITName:         "callback-8ce8588e75ea",
		CallOperationID: 2147483655,
	},
	{
		ID:              8,
		Identity:        "callback-9b79f3eb4945",
		WITName:         "callback-9b79f3eb4945",
		CallOperationID: 2147483656,
	},
	{
		ID:              9,
		Identity:        "callback-a3de14505458",
		WITName:         "callback-a3de14505458",
		CallOperationID: 2147483657,
	},
	{
		ID:              10,
		Identity:        "callback-a5d0afa3c957",
		WITName:         "callback-a5d0afa3c957",
		CallOperationID: 2147483658,
	},
	{
		ID:              11,
		Identity:        "callback-bf78377c58d5",
		WITName:         "callback-bf78377c58d5",
		CallOperationID: 2147483659,
	},
	{
		ID:              12,
		Identity:        "callback-d4c80bbf993f",
		WITName:         "callback-d4c80bbf993f",
		CallOperationID: 2147483660,
	},
	{
		ID:              13,
		Identity:        "callback-f39d53d38ffd",
		WITName:         "callback-f39d53d38ffd",
		CallOperationID: 2147483661,
	},
	{
		ID:              14,
		Identity:        "context.CancelFunc",
		WITName:         "cancel-func",
		CallOperationID: 2147483662,
	},
	{
		ID:              15,
		Identity:        "go.minekube.com/brigodier.CommandFunc",
		WITName:         "command-func",
		CallOperationID: 2147483663,
	},
	{
		ID:              16,
		Identity:        "go.minekube.com/gate/pkg/util/permission.Func",
		WITName:         "gate-func",
		CallOperationID: 2147483664,
	},
	{
		ID:              17,
		Identity:        "go.minekube.com/gate/pkg/edition/java/auth.HasJoinedURLFn",
		WITName:         "has-joined-url-fn",
		CallOperationID: 2147483665,
	},
	{
		ID:              18,
		Identity:        "go.minekube.com/gate/pkg/gate.LoadConfigFunc",
		WITName:         "load-config-func",
		CallOperationID: 2147483666,
	},
	{
		ID:              19,
		Identity:        "go.minekube.com/gate/pkg/runtime/process.RunnableFunc",
		WITName:         "runnable-func",
		CallOperationID: 2147483667,
	},
	{
		ID:              20,
		Identity:        "iter.Seq[reflect.Method]",
		WITName:         "seq-4454e9c05542",
		CallOperationID: 2147483668,
	},
	{
		ID:              21,
		Identity:        "iter.Seq[reflect.Type]",
		WITName:         "seq-56a88aa8d577",
		CallOperationID: 2147483669,
	},
	{
		ID:              22,
		Identity:        "iter.Seq[reflect.StructField]",
		WITName:         "seq-b074101856aa",
		CallOperationID: 2147483670,
	},
	{
		ID:              23,
		Identity:        "go.minekube.com/gate/pkg/gate.StartOption",
		WITName:         "start-option",
		CallOperationID: 2147483671,
	},
	{
		ID:              24,
		Identity:        "go.minekube.com/gate/pkg/command.SuggestFunc",
		WITName:         "suggest-func",
		CallOperationID: 2147483672,
	},
}

func RegisterGeneratedCallbacks(host *dispatch.Host) error {
	if err := host.Register(dispatch.Operation{
		ID:       2147483649,
		Identity: "callback-0105467f2bef#call",
		Handler:  generatedCallbackDispatch0001,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483650,
		Identity: "callback-1178afb46377#call",
		Handler:  generatedCallbackDispatch0002,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483651,
		Identity: "callback-1f86eef915ce#call",
		Handler:  generatedCallbackDispatch0003,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483652,
		Identity: "callback-2053c44117ea#call",
		Handler:  generatedCallbackDispatch0004,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483653,
		Identity: "callback-2c1c5989286b#call",
		Handler:  generatedCallbackDispatch0005,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483654,
		Identity: "callback-4e5db8a68395#call",
		Handler:  generatedCallbackDispatch0006,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483655,
		Identity: "callback-8ce8588e75ea#call",
		Handler:  generatedCallbackDispatch0007,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483656,
		Identity: "callback-9b79f3eb4945#call",
		Handler:  generatedCallbackDispatch0008,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483657,
		Identity: "callback-a3de14505458#call",
		Handler:  generatedCallbackDispatch0009,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483658,
		Identity: "callback-a5d0afa3c957#call",
		Handler:  generatedCallbackDispatch0010,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483659,
		Identity: "callback-bf78377c58d5#call",
		Handler:  generatedCallbackDispatch0011,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483660,
		Identity: "callback-d4c80bbf993f#call",
		Handler:  generatedCallbackDispatch0012,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483661,
		Identity: "callback-f39d53d38ffd#call",
		Handler:  generatedCallbackDispatch0013,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483662,
		Identity: "context.CancelFunc#call",
		Handler:  generatedCallbackDispatch0014,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483663,
		Identity: "go.minekube.com/brigodier.CommandFunc#call",
		Handler:  generatedCallbackDispatch0015,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483664,
		Identity: "go.minekube.com/gate/pkg/util/permission.Func#call",
		Handler:  generatedCallbackDispatch0016,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483665,
		Identity: "go.minekube.com/gate/pkg/edition/java/auth.HasJoinedURLFn#call",
		Handler:  generatedCallbackDispatch0017,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483666,
		Identity: "go.minekube.com/gate/pkg/gate.LoadConfigFunc#call",
		Handler:  generatedCallbackDispatch0018,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483667,
		Identity: "go.minekube.com/gate/pkg/runtime/process.RunnableFunc#call",
		Handler:  generatedCallbackDispatch0019,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483668,
		Identity: "iter.Seq[reflect.Method]#call",
		Handler:  generatedCallbackDispatch0020,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483669,
		Identity: "iter.Seq[reflect.Type]#call",
		Handler:  generatedCallbackDispatch0021,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483670,
		Identity: "iter.Seq[reflect.StructField]#call",
		Handler:  generatedCallbackDispatch0022,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483671,
		Identity: "go.minekube.com/gate/pkg/gate.StartOption#call",
		Handler:  generatedCallbackDispatch0023,
	}); err != nil {
		return err
	}
	if err := host.Register(dispatch.Operation{
		ID:       2147483672,
		Identity: "go.minekube.com/gate/pkg/command.SuggestFunc#call",
		Handler:  generatedCallbackDispatch0024,
	}); err != nil {
		return err
	}
	return nil
}

func generatedCallbackDispatch0001(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483649,
		Identity: "callback-0105467f2bef#call",
	}, arguments)
}

func generatedCallbackDispatch0002(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483650,
		Identity: "callback-1178afb46377#call",
	}, arguments)
}

func generatedCallbackDispatch0003(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483651,
		Identity: "callback-1f86eef915ce#call",
	}, arguments)
}

func generatedCallbackDispatch0004(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483652,
		Identity: "callback-2053c44117ea#call",
	}, arguments)
}

func generatedCallbackDispatch0005(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483653,
		Identity: "callback-2c1c5989286b#call",
	}, arguments)
}

func generatedCallbackDispatch0006(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483654,
		Identity: "callback-4e5db8a68395#call",
	}, arguments)
}

func generatedCallbackDispatch0007(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483655,
		Identity: "callback-8ce8588e75ea#call",
	}, arguments)
}

func generatedCallbackDispatch0008(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483656,
		Identity: "callback-9b79f3eb4945#call",
	}, arguments)
}

func generatedCallbackDispatch0009(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483657,
		Identity: "callback-a3de14505458#call",
	}, arguments)
}

func generatedCallbackDispatch0010(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483658,
		Identity: "callback-a5d0afa3c957#call",
	}, arguments)
}

func generatedCallbackDispatch0011(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483659,
		Identity: "callback-bf78377c58d5#call",
	}, arguments)
}

func generatedCallbackDispatch0012(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483660,
		Identity: "callback-d4c80bbf993f#call",
	}, arguments)
}

func generatedCallbackDispatch0013(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483661,
		Identity: "callback-f39d53d38ffd#call",
	}, arguments)
}

func generatedCallbackDispatch0014(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483662,
		Identity: "context.CancelFunc#call",
	}, arguments)
}

func generatedCallbackDispatch0015(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483663,
		Identity: "go.minekube.com/brigodier.CommandFunc#call",
	}, arguments)
}

func generatedCallbackDispatch0016(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483664,
		Identity: "go.minekube.com/gate/pkg/util/permission.Func#call",
	}, arguments)
}

func generatedCallbackDispatch0017(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483665,
		Identity: "go.minekube.com/gate/pkg/edition/java/auth.HasJoinedURLFn#call",
	}, arguments)
}

func generatedCallbackDispatch0018(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483666,
		Identity: "go.minekube.com/gate/pkg/gate.LoadConfigFunc#call",
	}, arguments)
}

func generatedCallbackDispatch0019(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483667,
		Identity: "go.minekube.com/gate/pkg/runtime/process.RunnableFunc#call",
	}, arguments)
}

func generatedCallbackDispatch0020(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483668,
		Identity: "iter.Seq[reflect.Method]#call",
	}, arguments)
}

func generatedCallbackDispatch0021(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483669,
		Identity: "iter.Seq[reflect.Type]#call",
	}, arguments)
}

func generatedCallbackDispatch0022(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483670,
		Identity: "iter.Seq[reflect.StructField]#call",
	}, arguments)
}

func generatedCallbackDispatch0023(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483671,
		Identity: "go.minekube.com/gate/pkg/gate.StartOption#call",
	}, arguments)
}

func generatedCallbackDispatch0024(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {
	return host.CallResource(ctx, dispatch.Operation{
		ID:       2147483672,
		Identity: "go.minekube.com/gate/pkg/command.SuggestFunc#call",
	}, arguments)
}
