/* Code generated by gate-wasm-gen; DO NOT EDIT. */
#ifndef GATE_WASM_GENERATED_H
#define GATE_WASM_GENERATED_H

#include <stdint.h>

#define GATE_WASM_GENERATOR_FORMAT 1
#define GATE_WASM_ABI_SCHEMA_VERSION 1
#define GATE_WASM_OPERATION_COUNT 1877
#define GATE_WASM_WIT_HASH "1fc6cec81933f7829b1ead2abc702a8f6699b78d557671c29ae1d092e703ec99"
#define GATE_WASM_ABI_LAYOUT_HASH "320d49296bb4e08ac043567eee1bd2a572db7d5ef37464b64a6d3c3458ba41b7"

typedef uint64_t gate_wasm_handle;
typedef uint32_t gate_wasm_discriminant;

typedef struct gate_wasm_borrowed_buffer {
  uint64_t pointer;
  uint64_t length;
} gate_wasm_borrowed_buffer;

typedef struct gate_wasm_owned_buffer {
  uint64_t pointer;
  uint64_t length;
  uint64_t capacity;
} gate_wasm_owned_buffer;

#endif
