/* Code generated by gate-wasm-gen; DO NOT EDIT. */
#ifndef GATE_WASM_GENERATED_H
#define GATE_WASM_GENERATED_H

#include <stdint.h>

#define GATE_WASM_GENERATOR_FORMAT 1
#define GATE_WASM_ABI_SCHEMA_VERSION 1
#define GATE_WASM_OPERATION_COUNT 1923
#define GATE_WASM_WIT_HASH "05844571b07f3e19787939aa5fa98328c13acef7ab49ba74bb3388ab713cd2c3"
#define GATE_WASM_ABI_LAYOUT_HASH "42360cdec0d21a8a7a18c5f90242140dd71b2ff6fa041952d046b6e4c890880c"

typedef uint64_t gate_wasm_handle;
typedef uint32_t gate_wasm_discriminant;

typedef struct gate_wasm_borrowed_buffer {
  uint64_t pointer;
  uint64_t length;
} gate_wasm_borrowed_buffer;

typedef struct gate_wasm_owned_buffer {
  uint64_t pointer;
  uint64_t length;
  uint64_t capacity;
} gate_wasm_owned_buffer;

#endif
