version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      # Add any other Jaeger-specific environment variables if needed
    ports:
      # OTLP receiver ports (gRPC and HTTP)
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
      # Jaeger UI
      - '16686:16686' # Jaeger Query UI
      # Other Jaeger ports (optional, for different protocols)
      # - "6831:6831/udp" # Jaeger agent (jaeger.thrift over compact thrift protocol)
      # - "6832:6832/udp" # Jaeger agent (jaeger.thrift over binary thrift protocol)
      # - "5778:5778"     # Jaeger agent (serve configs)
      # - "14268:14268"   # Jaeger collector (jaeger.thrift directly from clients)
      # - "9411:9411"     # Jaeger collector (Zipkin compatible endpoint)
    networks:
      - otel-jaeger-net # Optional: use a dedicated network or an existing one

networks:
  otel-jaeger-net:
    driver: bridge
