global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889'] # This is scraped by Prometheus
    metric_relabel_configs:
      # Convert duration_seconds to latency for Tempo compatibility
      - source_labels: [__name__]
        regex: 'traces_spanmetrics_duration_seconds(_bucket|_sum|_count)?'
        target_label: __name__
        replacement: 'traces_spanmetrics_latency${1}'
