# This is a simplified config where the rest of the
# settings are omitted and will be set by default.
# See config.yml for the full configuration options.
config:
  bind: 0.0.0.0:25565
  servers:
    velocityserver1: localhost:25568
  try:
    - velocityserver1
  forwarding:
    mode: velocity
    velocitySecret: my-secret
