{
 "title": "Gate Overview",
 "tags": [
  "gate",
  "otel"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource (Prometheus)", "query": "prometheus" },
   { "name": "DS_TEMPO", "label": "Datasource (Tempo)", "query": "tempo" },
   {
    "name": "service_name_filter",
    "label": "Job (Service Name)",
    "query": {
     "query": "label_values(process_runtime_go_goroutines, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Player Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gate_player_count_ratio{job=~\"$service_name_filter\"})",
     "legendFormat": "Total Players"
    }
   ]
  },
  {
   "title": "Registered Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gate_registered_servers_ratio{job=~\"$service_name_filter\"})",
     "legendFormat": "Registered Servers"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_goroutines{job=~\"$service_name_filter\"}) by (job, instance)",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Go Memory Usage (Alloc Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_go_mem_heap_alloc_bytes{job=~\"$service_name_filter\"}) by (job, instance)",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "634733e6", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "cf87943a877ce5560ecac80822086d73",
     "tableType": "traces"
    }
   ]
  }
 ]
}