apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gate-servicemonitor
  namespace: monitoring # Or the namespace where kube-prometheus-stack is installed/configured to watch
  labels:
    # These labels are often used by Prometheus Operator to discover ServiceMonitors.
    # Check your kube-prometheus-stack configuration for the correct labels.
    # A common one is just 'release: prometheus' if you named your helm release 'prometheus'.
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gate # This must match the labels on your Gate Service
  namespaceSelector:
    matchNames:
      - default # Or the namespace where your Gate service is running
  endpoints:
    - port: metrics # This must match the name of the metrics port in your Gate Service
      interval: 15s # Optional: scrape interval
      path: /metrics # Optional: if Gate's OTEL_METRICS_SERVER_PATH is different
      # honorLabels: true # Useful if you want to keep labels from the pods/services, like instance IPs
