package generate

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"

	"go.minekube.com/gate/internal/wasm/model"
)

// Contract identifies one generated Gate component contract.
type Contract struct {
	Generated        string `json:"_generated"`
	GeneratorFormat  uint32 `json:"generatorFormat"`
	ABISchemaVersion uint32 `json:"abiSchemaVersion"`
	ABILayoutHash    string `json:"abiLayoutHash"`
	CanonicalHash    string `json:"canonicalHash"`
	WITHash          string `json:"witHash"`
	PackageCount     int    `json:"packageCount"`
	DeclarationCount int    `json:"declarationCount"`
	OperationCount   int    `json:"operationCount"`
}

// RenderContract renders deterministic contract metadata.
func RenderContract(api *model.API, wit []byte) ([]byte, error) {
	manifest, err := RenderManifest(api)
	if err != nil {
		return nil, err
	}
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	abi, err := BuildABI(normalized)
	if err != nil {
		return nil, fmt.Errorf("build ABI schema: %w", err)
	}
	operations, err := Operations(normalized)
	if err != nil {
		return nil, fmt.Errorf("build operation manifest: %w", err)
	}
	canonicalHash := sha256.Sum256(manifest)
	witHash := sha256.Sum256(wit)
	contract := Contract{
		Generated:        "Code generated by gate-wasm-gen; DO NOT EDIT.",
		GeneratorFormat:  normalized.FormatVersion,
		ABISchemaVersion: abi.Version,
		ABILayoutHash:    abi.Fingerprint,
		CanonicalHash:    hex.EncodeToString(canonicalHash[:]),
		WITHash:          hex.EncodeToString(witHash[:]),
		PackageCount:     len(normalized.Packages),
		DeclarationCount: len(normalized.Declarations),
		OperationCount:   len(operations),
	}
	rendered, err := json.MarshalIndent(contract, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal contract metadata: %w", err)
	}
	return append(rendered, '\n'), nil
}
