package generate

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"go.minekube.com/gate/internal/wasm/analyze"
	"go.minekube.com/gate/internal/wasm/model"
)

func TestRenderWITMatchesGoldenAndIsDeterministic(t *testing.T) {
	api := simpleAPI()

	first, err := RenderWIT(api)
	require.NoError(t, err)
	expected, err := os.ReadFile("testdata/simple.golden.wit")
	require.NoError(t, err)
	require.Equal(t, string(expected), string(first))

	shuffled := cloneAPI(t, api)
	slices.Reverse(shuffled.Packages)
	slices.Reverse(shuffled.Declarations)
	for index := range shuffled.Packages {
		slices.Reverse(shuffled.Packages[index].Declarations)
	}
	second, err := RenderWIT(shuffled)
	require.NoError(t, err)
	require.Equal(t, first, second)
}

func TestManifestAndContractHashesAreDeterministic(t *testing.T) {
	api := simpleAPI()
	wit, err := RenderWIT(api)
	require.NoError(t, err)
	manifest, err := RenderManifest(api)
	require.NoError(t, err)
	contractBytes, err := RenderContract(api, wit)
	require.NoError(t, err)

	var generatedManifest Manifest
	require.NoError(t, json.Unmarshal(manifest, &generatedManifest))
	require.Equal(t, "Code generated by gate-wasm-gen; DO NOT EDIT.", generatedManifest.Generated)
	require.Equal(t, api.Packages, generatedManifest.Packages)
	require.Equal(t, api.Declarations, generatedManifest.Declarations)

	var contract Contract
	require.NoError(t, json.Unmarshal(contractBytes, &contract))
	require.EqualValues(t, 1, contract.GeneratorFormat)
	require.EqualValues(t, 1, contract.ABISchemaVersion)
	require.Len(t, contract.ABILayoutHash, 64)
	require.Len(t, contract.CanonicalHash, 64)
	require.Len(t, contract.WITHash, 64)
	require.Equal(t, len(api.Packages), contract.PackageCount)
	require.Equal(t, len(api.Declarations), contract.DeclarationCount)
	operations, err := Operations(api)
	require.NoError(t, err)
	require.Equal(t, len(operations), contract.OperationCount)

	again, err := RenderContract(cloneAPI(t, api), wit)
	require.NoError(t, err)
	require.Equal(t, contractBytes, again)

	changed := cloneAPI(t, api)
	sample := declarationPointer(
		t,
		changed,
		"example.com/project/pkg/shapes.Sample",
	)
	sample.Type.Fields[0].Type.Kind = model.TypeU32
	changedWIT, err := RenderWIT(changed)
	require.NoError(t, err)
	changedContractBytes, err := RenderContract(changed, changedWIT)
	require.NoError(t, err)
	var changedContract Contract
	require.NoError(t, json.Unmarshal(changedContractBytes, &changedContract))
	require.NotEqual(t, contract.CanonicalHash, changedContract.CanonicalHash)
	require.NotEqual(t, contract.WITHash, changedContract.WITHash)
}

func TestStructuralCompatibilityAcceptsAdditionsAndRejectsBreakingPaths(t *testing.T) {
	required := simpleAPI()
	host := cloneAPI(t, required)
	host.Declarations = append(host.Declarations, model.Declaration{
		Identity:    "example.com/project/pkg/shapes.Added",
		PackagePath: "example.com/project/pkg/shapes",
		GoName:      "Added",
		WITName:     "added",
		Kind:        model.DeclarationFunction,
		Callable:    &model.Callable{},
		Coverage:    model.Coverage{State: model.CoverageRepresented},
	})
	host.Packages[0].Declarations = append(
		host.Packages[0].Declarations,
		"example.com/project/pkg/shapes.Added",
	)
	require.NoError(t, host.Normalize())
	require.NoError(t, CheckCompatibility(required, host))

	removed := cloneAPI(t, required)
	for index, declaration := range removed.Declarations {
		if declaration.Identity == "example.com/project/pkg/shapes.Sample" {
			removed.Declarations = append(
				removed.Declarations[:index],
				removed.Declarations[index+1:]...,
			)
			break
		}
	}
	require.ErrorContains(
		t,
		CheckCompatibility(required, removed),
		"example.com/project/pkg/shapes.Sample: missing",
	)

	changed := cloneAPI(t, required)
	sample := declarationPointer(
		t,
		changed,
		"example.com/project/pkg/shapes.Sample",
	)
	sample.Type.Fields[0].Type.Kind = model.TypeU32
	require.ErrorContains(
		t,
		CheckCompatibility(required, changed),
		"example.com/project/pkg/shapes.Sample.type.fields[0].type.kind",
	)
}

func TestRenderCompleteGateAPI(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", "..", ".."))
	require.NoError(t, err)
	api, err := analyze.Analyze(context.Background(), analyze.GateOptions(root))
	require.NoError(t, err)

	wit, err := RenderWIT(api)
	require.NoError(t, err)
	require.Greater(t, len(wit), 100_000)
	require.Contains(t, string(wit), "interface pkg-edition-java-proxy {")
	require.Contains(t, string(wit), "world gate-plugin {")
	require.Equal(t, len(api.Packages), strings.Count(string(wit), "\n  import "))

	manifest, err := RenderManifest(api)
	require.NoError(t, err)
	var rendered Manifest
	require.NoError(t, json.Unmarshal(manifest, &rendered))
	require.Equal(t, len(api.Declarations), len(rendered.Declarations))
}

func simpleAPI() *model.API {
	sample := model.Type{
		Identity:  "example.com/project/pkg/shapes.Sample",
		WITName:   "sample",
		GoType:    "example.com/project/pkg/shapes.Sample",
		Kind:      model.TypeRecord,
		Ownership: model.OwnershipCopy,
		Lifetime:  model.LifetimeValue,
		Fields: []model.Field{
			{
				GoName: "Text", WITName: "text",
				Type: scalarType("string", model.TypeString),
			},
			{
				GoName: "Tags", WITName: "tags",
				Type: model.Type{
					GoType: "[]string", Kind: model.TypeList,
					Ownership: model.OwnershipCopy,
					Lifetime:  model.LifetimeValue,
					Nullable:  true,
					Element:   typePointer(scalarType("string", model.TypeString)),
				},
			},
		},
	}
	proxy := model.Type{
		Identity:     "go.minekube.com/gate/pkg/edition/java/proxy.Proxy",
		WITName:      "proxy",
		GoType:       "*go.minekube.com/gate/pkg/edition/java/proxy.Proxy",
		Kind:         model.TypeResource,
		Ownership:    model.OwnershipBorrow,
		Lifetime:     model.LifetimePlugin,
		Nullable:     true,
		ResourceType: "go.minekube.com/gate/pkg/edition/java/proxy.Proxy",
	}
	handler := model.Type{
		Identity:     "example.com/project/pkg/shapes.Handler",
		WITName:      "handler",
		GoType:       "example.com/project/pkg/shapes.Handler",
		Kind:         model.TypeCallback,
		Ownership:    model.OwnershipOwn,
		Lifetime:     model.LifetimePlugin,
		Nullable:     true,
		ResourceType: "example.com/project/pkg/shapes.Handler",
		Callback: &model.Callback{
			Identity:  "example.com/project/pkg/shapes.Handler",
			Direction: model.CallbackHostToGuest,
			Callable: model.Callable{
				Parameters: []model.Parameter{{
					GoName: "Input", WITName: "input",
					Type: scalarType("string", model.TypeString),
				}},
				Results: []model.Parameter{{
					GoName: "OK", WITName: "ok",
					Type: scalarType("bool", model.TypeBool),
				}},
			},
			Retained:  true,
			Reentrant: true,
		},
	}
	api := &model.API{
		FormatVersion: 1,
		ModulePath:    "example.com/project",
		Packages: []model.Package{{
			Path:    "example.com/project/pkg/shapes",
			Name:    "shapes",
			WITName: "pkg-shapes",
			Declarations: []string{
				"example.com/project/pkg/shapes.Handler",
				"example.com/project/pkg/shapes.Register",
				"example.com/project/pkg/shapes.Sample",
				"example.com/project/pkg/shapes.Transform",
			},
		}},
		Declarations: []model.Declaration{
			{
				Identity:    "example.com/project/pkg/shapes.Sample",
				PackagePath: "example.com/project/pkg/shapes",
				GoName:      "Sample",
				WITName:     "sample",
				Kind:        model.DeclarationType,
				Type:        &sample,
				Coverage:    model.Coverage{State: model.CoverageRepresented},
			},
			{
				Identity:    "example.com/project/pkg/shapes.Handler",
				PackagePath: "example.com/project/pkg/shapes",
				GoName:      "Handler",
				WITName:     "handler",
				Kind:        model.DeclarationType,
				Type:        &handler,
				Coverage:    model.Coverage{State: model.CoverageRepresented},
			},
			{
				Identity:    "example.com/project/pkg/shapes.Transform",
				PackagePath: "example.com/project/pkg/shapes",
				GoName:      "Transform",
				WITName:     "transform",
				Kind:        model.DeclarationFunction,
				Callable: &model.Callable{
					Parameters: []model.Parameter{
						{GoName: "Proxy", WITName: "proxy", Type: proxy},
						{GoName: "Input", WITName: "input", Type: sample},
					},
					Results: []model.Parameter{{
						GoName: "Output", WITName: "output", Type: sample,
					}},
					Error: &model.ErrorBehavior{Fallback: true},
				},
				Coverage: model.Coverage{State: model.CoverageRepresented},
			},
			{
				Identity:    "example.com/project/pkg/shapes.Register",
				PackagePath: "example.com/project/pkg/shapes",
				GoName:      "Register",
				WITName:     "register",
				Kind:        model.DeclarationFunction,
				Callable: &model.Callable{
					Parameters: []model.Parameter{{
						GoName: "Handler", WITName: "handler", Type: handler,
					}},
					Error: &model.ErrorBehavior{Fallback: true},
				},
				Coverage: model.Coverage{State: model.CoverageRepresented},
			},
		},
	}
	if err := api.Normalize(); err != nil {
		panic(err)
	}
	return api
}

func scalarType(goType string, kind model.TypeKind) model.Type {
	return model.Type{
		GoType: goType, Kind: kind,
		Ownership: model.OwnershipCopy,
		Lifetime:  model.LifetimeValue,
	}
}

func typePointer(value model.Type) *model.Type {
	return &value
}

func cloneAPI(t *testing.T, api *model.API) *model.API {
	t.Helper()
	encoded, err := json.Marshal(api)
	require.NoError(t, err)
	var cloned model.API
	require.NoError(t, json.Unmarshal(encoded, &cloned))
	return &cloned
}

func declarationPointer(
	t *testing.T,
	api *model.API,
	identity string,
) *model.Declaration {
	t.Helper()
	for index := range api.Declarations {
		if api.Declarations[index].Identity == identity {
			return &api.Declarations[index]
		}
	}
	t.Fatalf("declaration %q not found", identity)
	return nil
}
