package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"

	"go.minekube.com/gate/internal/wasm/model"
)

// RenderGoValues renders the Go side of the synchronized generated ABI
// descriptors. Typed converters and dispatchers consume these descriptors.
func RenderGoValues(api *model.API) ([]byte, error) {
	schema, err := BuildABI(api)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by gate-wasm-gen; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package api")
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"// GeneratedABISchemaVersion is ABI schema version %d.\n",
		schema.Version,
	)
	fmt.Fprintf(
		&output,
		"const GeneratedABISchemaVersion uint32 = %d\n",
		schema.Version,
	)
	fmt.Fprintf(
		&output,
		"const GeneratedABILayoutFingerprint = %s\n",
		strconv.Quote(schema.Fingerprint),
	)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type GeneratedValueLayout struct {")
	fmt.Fprintln(&output, "\tIdentity string")
	fmt.Fprintln(&output, "\tDirection string")
	fmt.Fprintln(&output, "\tKind string")
	fmt.Fprintln(&output, "\tSize uint64")
	fmt.Fprintln(&output, "\tAlignment uint32")
	fmt.Fprintln(&output, "\tAllocator string")
	fmt.Fprintln(&output, "\tFreeOperation string")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"var GeneratedValueLayouts = [...]GeneratedValueLayout{",
	)
	for _, entry := range schema.Layouts {
		fmt.Fprintln(&output, "\t{")
		fmt.Fprintf(&output, "\t\tIdentity: %s,\n", strconv.Quote(entry.Identity))
		fmt.Fprintf(
			&output,
			"\t\tDirection: %s,\n",
			strconv.Quote(string(entry.Direction)),
		)
		fmt.Fprintf(
			&output,
			"\t\tKind: %s,\n",
			strconv.Quote(string(entry.Layout.Kind)),
		)
		fmt.Fprintf(&output, "\t\tSize: %d,\n", entry.Layout.Size)
		fmt.Fprintf(&output, "\t\tAlignment: %d,\n", entry.Layout.Alignment)
		fmt.Fprintf(
			&output,
			"\t\tAllocator: %s,\n",
			strconv.Quote(string(entry.Layout.Allocator)),
		)
		fmt.Fprintf(
			&output,
			"\t\tFreeOperation: %s,\n",
			strconv.Quote(entry.Layout.FreeOperation),
		)
		fmt.Fprintln(&output, "\t},")
	}
	fmt.Fprintln(&output, "}")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go values: %w", err)
	}
	return formatted, nil
}
