package generate

import (
	"encoding/json"
	"fmt"

	"go.minekube.com/gate/internal/wasm/model"
)

// Manifest is the generated, complete public API coverage record.
type Manifest struct {
	Generated       string               `json:"_generated"`
	GeneratorFormat uint32               `json:"generatorFormat"`
	ModulePath      string               `json:"modulePath"`
	Packages        []model.Package      `json:"packages"`
	Declarations    []model.Declaration  `json:"declarations"`
	Operations      []GeneratedOperation `json:"operations"`
}

// RenderManifest renders complete declaration coverage as deterministic JSON.
func RenderManifest(api *model.API) ([]byte, error) {
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	operations, err := Operations(normalized)
	if err != nil {
		return nil, err
	}
	manifest := Manifest{
		Generated:       "Code generated by gate-wasm-gen; DO NOT EDIT.",
		GeneratorFormat: normalized.FormatVersion,
		ModulePath:      normalized.ModulePath,
		Packages:        normalized.Packages,
		Declarations:    normalized.Declarations,
		Operations:      operations,
	}
	rendered, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal canonical API manifest: %w", err)
	}
	return append(rendered, '\n'), nil
}

func normalizedAPI(api *model.API) (*model.API, error) {
	if api == nil {
		return nil, fmt.Errorf("canonical API is required")
	}
	encoded, err := json.Marshal(api)
	if err != nil {
		return nil, fmt.Errorf("clone canonical API: %w", err)
	}
	var cloned model.API
	if err := json.Unmarshal(encoded, &cloned); err != nil {
		return nil, fmt.Errorf("clone canonical API: %w", err)
	}
	if err := cloned.Normalize(); err != nil {
		return nil, fmt.Errorf("normalize canonical API: %w", err)
	}
	return &cloned, nil
}
