package generate

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"slices"
	"strings"

	"go.minekube.com/gate/internal/wasm/model"
)

const generatedHeader = "// Code generated by gate-wasm-gen; DO NOT EDIT."

// RenderWIT renders the canonical model as a language-neutral WIT package.
func RenderWIT(api *model.API) ([]byte, error) {
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	registry, err := newWITRegistry(normalized)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, generatedHeader)
	fmt.Fprintln(&output, "package minekube:gate@0.1.0;")
	fmt.Fprintln(&output)
	registry.renderTypes(&output)
	fmt.Fprintln(&output)
	renderCallbacksInterface(&output, registry)
	fmt.Fprintln(&output)

	declarations := make(map[string]model.Declaration, len(normalized.Declarations))
	for _, declaration := range normalized.Declarations {
		declarations[declaration.Identity] = declaration
	}
	for packageIndex, pkg := range normalized.Packages {
		renderPackageInterface(&output, pkg, declarations, registry)
		if packageIndex+1 < len(normalized.Packages) {
			fmt.Fprintln(&output)
		}
	}
	if len(normalized.Packages) > 0 {
		fmt.Fprintln(&output)
	}
	renderPluginInterface(&output, registry)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "world gate-plugin {")
	for _, pkg := range normalized.Packages {
		fmt.Fprintf(&output, "  import %s;\n", pkg.WITName)
	}
	fmt.Fprintln(&output, "  import gate-callbacks;")
	fmt.Fprintln(&output, "  export plugin;")
	fmt.Fprintln(&output, "}")
	return output.Bytes(), nil
}

type witPosition uint8

const (
	witInput witPosition = iota
	witOutput
	witNested
)

type witDefinition struct {
	identity      string
	preferredName string
	name          string
	typ           model.Type
	aliasTarget   *model.Type
	documentation string
}

type witRegistry struct {
	definitions map[string]*witDefinition
}

func newWITRegistry(api *model.API) (*witRegistry, error) {
	registry := &witRegistry{
		definitions: make(map[string]*witDefinition),
	}
	registry.addType(model.Type{
		Identity:     "context.Context",
		WITName:      "context",
		GoType:       "context.Context",
		Kind:         model.TypeResource,
		Ownership:    model.OwnershipBorrow,
		Lifetime:     model.LifetimePlugin,
		ResourceType: "context.Context",
	})
	registry.addType(model.Type{
		Identity:     "go.minekube.com/gate/pkg/edition/java/proxy.Proxy",
		WITName:      "proxy",
		GoType:       "*go.minekube.com/gate/pkg/edition/java/proxy.Proxy",
		Kind:         model.TypeResource,
		Ownership:    model.OwnershipBorrow,
		Lifetime:     model.LifetimePlugin,
		ResourceType: "go.minekube.com/gate/pkg/edition/java/proxy.Proxy",
	})
	for _, declaration := range api.Declarations {
		if declaration.Coverage.State != model.CoverageRepresented {
			continue
		}
		if declaration.Type != nil {
			switch declaration.Kind {
			case model.DeclarationAlias:
				target := *declaration.Type
				registry.addDefinition(witDefinition{
					identity:      declaration.Identity,
					preferredName: declaration.WITName,
					aliasTarget:   &target,
					documentation: declaration.Documentation,
				})
				registry.addType(target)
			case model.DeclarationType:
				typ := *declaration.Type
				typ.Identity = declaration.Identity
				typ.WITName = declaration.WITName
				registry.addDefinition(witDefinition{
					identity:      declaration.Identity,
					preferredName: declaration.WITName,
					typ:           typ,
					documentation: declaration.Documentation,
				})
				registry.addTypeChildren(typ)
			default:
				registry.addType(*declaration.Type)
			}
		}
		if declaration.Callable != nil {
			registry.addCallable(*declaration.Callable)
		}
		if declaration.Receiver != nil {
			receiverIdentity := declaration.Receiver.TypeIdentity
			if declaration.Receiver.Pointer {
				if definition := registry.definitions[receiverIdentity]; definition != nil &&
					definition.typ.Kind != model.TypeResource {
					receiverIdentity += "#pointer"
				}
			}
			if _, exists := registry.definitions[receiverIdentity]; !exists {
				registry.addType(model.Type{
					Identity:     receiverIdentity,
					WITName:      preferredTypeName(receiverIdentity),
					GoType:       receiverIdentity,
					Kind:         model.TypeResource,
					Ownership:    model.OwnershipBorrow,
					Lifetime:     model.LifetimeGateOwned,
					ResourceType: receiverIdentity,
				})
			}
		}
	}
	if err := registry.assignNames(); err != nil {
		return nil, err
	}
	return registry, nil
}

func (r *witRegistry) addCallable(callable model.Callable) {
	for _, parameter := range callable.Parameters {
		r.addType(parameter.Type)
	}
	for _, result := range callable.Results {
		r.addType(result.Type)
	}
}

func (r *witRegistry) addType(typ model.Type) {
	r.addTypeChildren(typ)
	if !needsWITDefinition(typ) {
		return
	}
	identity := witTypeIdentity(typ)
	r.addDefinition(witDefinition{
		identity:      identity,
		preferredName: preferredTypeNameFor(typ, identity),
		typ:           typ,
	})
}

func (r *witRegistry) addTypeChildren(typ model.Type) {
	if typ.Element != nil {
		r.addType(*typ.Element)
	}
	if typ.Key != nil {
		r.addType(*typ.Key)
	}
	for _, field := range typ.Fields {
		r.addType(field.Type)
	}
	for _, variant := range typ.Cases {
		if variant.Type != nil {
			r.addType(*variant.Type)
		}
	}
	for _, tuple := range typ.Tuple {
		r.addType(tuple)
	}
	if typ.Callback != nil {
		r.addCallable(typ.Callback.Callable)
	}
}

func (r *witRegistry) addDefinition(definition witDefinition) {
	if definition.identity == "" {
		panic("WIT definition identity is empty")
	}
	if existing := r.definitions[definition.identity]; existing != nil {
		if existing.documentation == "" {
			existing.documentation = definition.documentation
		}
		if existing.preferredName == "" {
			existing.preferredName = definition.preferredName
		}
		if existing.typ.Kind == "" && definition.typ.Kind != "" {
			existing.typ = definition.typ
		}
		if existing.aliasTarget == nil && definition.aliasTarget != nil {
			existing.aliasTarget = definition.aliasTarget
		}
		return
	}
	copied := definition
	r.definitions[definition.identity] = &copied
}

func (r *witRegistry) assignNames() error {
	groups := make(map[string][]*witDefinition)
	for _, definition := range r.definitions {
		name := definition.preferredName
		if name == "" {
			name = preferredTypeName(definition.identity)
		}
		if name == "gate-error" {
			name += "-" + shortHash(definition.identity)
		}
		groups[name] = append(groups[name], definition)
	}
	assigned := map[string]string{"gate-error": "built-in gate error"}
	for base, group := range groups {
		slices.SortFunc(group, func(left, right *witDefinition) int {
			return strings.Compare(left.identity, right.identity)
		})
		for _, definition := range group {
			name := base
			if len(group) > 1 {
				name += "-" + shortHash(definition.identity)
			}
			if previous, exists := assigned[name]; exists {
				return fmt.Errorf(
					"WIT type name collision %q between %q and %q",
					name,
					previous,
					definition.identity,
				)
			}
			assigned[name] = definition.identity
			definition.name = name
		}
	}
	return nil
}

func (r *witRegistry) renderTypes(output *bytes.Buffer) {
	fmt.Fprintln(output, "interface gate-types {")
	fmt.Fprintln(output, "  record gate-error {")
	fmt.Fprintln(output, "    kind: string,")
	fmt.Fprintln(output, "    message: string,")
	fmt.Fprintln(output, "    operation: string,")
	fmt.Fprintln(output, "  }")

	definitions := make([]*witDefinition, 0, len(r.definitions))
	for _, definition := range r.definitions {
		definitions = append(definitions, definition)
	}
	slices.SortFunc(definitions, func(left, right *witDefinition) int {
		return strings.Compare(left.name, right.name)
	})
	for _, definition := range definitions {
		fmt.Fprintln(output)
		renderDocumentation(output, "  ", definition.documentation)
		r.renderDefinition(output, definition)
	}
	fmt.Fprintln(output, "}")
}

func (r *witRegistry) renderDefinition(output *bytes.Buffer, definition *witDefinition) {
	if definition.aliasTarget != nil {
		if definition.aliasTarget.Kind == model.TypeResource ||
			definition.aliasTarget.Kind == model.TypeCallback ||
			definition.aliasTarget.Kind == model.TypeDynamic {
			// WIT handle types cannot be named aliases. Give a Go alias its
			// own opaque resource identity so standard guest binding
			// generators can consume the contract.
			fmt.Fprintf(output, "  resource %s;\n", definition.name)
			return
		}
		fmt.Fprintf(
			output,
			"  type %s = %s;\n",
			definition.name,
			r.typeExpression(*definition.aliasTarget, witNested, nil, ""),
		)
		return
	}
	typ := definition.typ
	switch typ.Kind {
	case model.TypeResource, model.TypeCallback, model.TypeDynamic:
		fmt.Fprintf(output, "  resource %s;\n", definition.name)
	case model.TypeRecord:
		fmt.Fprintf(output, "  record %s {\n", definition.name)
		if len(typ.Fields) == 0 {
			// The component model rejects zero-field records. Preserve empty
			// Go value semantics with a generated zero-valued unit field.
			fmt.Fprintln(output, "    gate-unit: u8,")
		}
		for _, field := range typ.Fields {
			renderDocumentation(output, "    ", field.Documentation)
			fmt.Fprintf(
				output,
				"    %s: %s,\n",
				field.WITName,
				r.typeExpression(field.Type, witNested, nil, ""),
			)
		}
		fmt.Fprintln(output, "  }")
	case model.TypeVariant:
		fmt.Fprintf(output, "  variant %s {\n", definition.name)
		for _, variant := range typ.Cases {
			if variant.Type == nil {
				fmt.Fprintf(output, "    %s,\n", variant.WITName)
			} else {
				fmt.Fprintf(
					output,
					"    %s(%s),\n",
					variant.WITName,
					r.typeExpression(*variant.Type, witNested, nil, ""),
				)
			}
		}
		fmt.Fprintln(output, "  }")
	case model.TypeEnum:
		fmt.Fprintf(output, "  enum %s {\n", definition.name)
		for _, enumCase := range typ.Cases {
			fmt.Fprintf(output, "    %s,\n", enumCase.WITName)
		}
		fmt.Fprintln(output, "  }")
	case model.TypeFlags:
		fmt.Fprintf(output, "  flags %s {\n", definition.name)
		for _, flag := range typ.Cases {
			fmt.Fprintf(output, "    %s,\n", flag.WITName)
		}
		fmt.Fprintln(output, "  }")
	default:
		fmt.Fprintf(
			output,
			"  type %s = %s;\n",
			definition.name,
			r.typeExpression(typ, witNested, nil, definition.identity),
		)
	}
}

func renderPackageInterface(
	output *bytes.Buffer,
	pkg model.Package,
	declarations map[string]model.Declaration,
	registry *witRegistry,
) {
	fmt.Fprintf(output, "interface %s {\n", pkg.WITName)
	var operations []model.Declaration
	used := make(map[string]struct{})
	for _, identity := range pkg.Declarations {
		declaration, exists := declarations[identity]
		if !exists ||
			declaration.Coverage.State != model.CoverageRepresented ||
			declaration.Kind == model.DeclarationType ||
			declaration.Kind == model.DeclarationAlias {
			continue
		}
		operations = append(operations, declaration)
		collectDeclarationUses(declaration, registry, used)
	}
	localNames := localTypeNames(used, operationNames(operations))
	renderUse(output, used, localNames)
	if len(used) > 0 && len(operations) > 0 {
		fmt.Fprintln(output)
	}
	for index, declaration := range operations {
		renderDocumentation(output, "  ", declaration.Documentation)
		registry.renderOperation(output, declaration, localNames)
		if index+1 < len(operations) {
			// Operations are intentionally compact; documentation remains
			// attached to the declaration immediately below it.
		}
	}
	fmt.Fprintln(output, "}")
}

func (r *witRegistry) renderOperation(
	output *bytes.Buffer,
	declaration model.Declaration,
	localNames map[string]string,
) {
	switch declaration.Kind {
	case model.DeclarationConstant:
		fmt.Fprintf(
			output,
			"  get-%s: func() -> %s;\n",
			declaration.WITName,
			r.typeExpression(*declaration.Type, witOutput, localNames, ""),
		)
	case model.DeclarationVariable:
		fmt.Fprintf(
			output,
			"  get-%s: func() -> %s;\n",
			declaration.WITName,
			r.typeExpression(*declaration.Type, witOutput, localNames, ""),
		)
		if declaration.Variable != nil && declaration.Variable.Writable {
			fmt.Fprintf(
				output,
				"  set-%s: func(value: %s);\n",
				declaration.WITName,
				r.typeExpression(*declaration.Type, witInput, localNames, ""),
			)
		}
	default:
		fmt.Fprintf(
			output,
			"  %s: %s;\n",
			declaration.WITName,
			r.callableExpression(declaration, localNames),
		)
	}
}

func (r *witRegistry) callableExpression(
	declaration model.Declaration,
	localNames map[string]string,
) string {
	callable := *declaration.Callable
	var parameters []string
	if declaration.Receiver != nil {
		receiverIdentity := declaration.Receiver.TypeIdentity
		definition := r.definitions[receiverIdentity]
		if declaration.Receiver.Pointer &&
			definition != nil &&
			definition.typ.Kind != model.TypeResource {
			receiverIdentity += "#pointer"
		}
		receiver := model.Type{
			Identity:     receiverIdentity,
			Kind:         model.TypeResource,
			Ownership:    model.OwnershipBorrow,
			Lifetime:     model.LifetimeGateOwned,
			ResourceType: receiverIdentity,
		}
		if definition := r.definitions[receiverIdentity]; definition != nil &&
			definition.typ.Kind != model.TypeResource {
			receiver = definition.typ
			receiver.Nullable = false
		}
		parameters = append(
			parameters,
			"self: "+r.typeExpression(receiver, witInput, localNames, ""),
		)
	}
	for _, parameter := range callable.Parameters {
		parameters = append(
			parameters,
			parameter.WITName+": "+
				r.typeExpression(parameter.Type, witInput, localNames, ""),
		)
	}
	return "func(" + strings.Join(parameters, ", ") + ")" +
		r.resultExpression(callable, localNames)
}

func (r *witRegistry) resultExpression(
	callable model.Callable,
	localNames map[string]string,
) string {
	var success string
	switch len(callable.Results) {
	case 0:
		success = "_"
	case 1:
		success = r.typeExpression(
			callable.Results[0].Type,
			witOutput,
			localNames,
			"",
		)
	default:
		results := make([]string, len(callable.Results))
		for index, result := range callable.Results {
			results[index] = r.typeExpression(
				result.Type,
				witOutput,
				localNames,
				"",
			)
		}
		success = "tuple<" + strings.Join(results, ", ") + ">"
	}
	if callable.Error != nil {
		return " -> result<" + success + ", gate-error>"
	}
	if len(callable.Results) == 0 {
		return ""
	}
	return " -> " + success
}

func renderPluginInterface(output *bytes.Buffer, registry *witRegistry) {
	contextName := registry.definitions["context.Context"].name
	proxyName := registry.definitions["go.minekube.com/gate/pkg/edition/java/proxy.Proxy"].name
	used := map[string]struct{}{
		"name:" + contextName: {},
		"name:" + proxyName:   {},
		"gate-error":          {},
	}
	callbacks := registry.callbacks()
	for _, definition := range callbacks {
		collectDefinitionUse(definition.identity, registry, used)
		for _, parameter := range definition.typ.Callback.Callable.Parameters {
			collectTypeUses(parameter.Type, registry, used)
		}
		for _, result := range definition.typ.Callback.Callable.Results {
			collectTypeUses(result.Type, registry, used)
		}
	}
	reserved := map[string]struct{}{
		"metadata": {},
		"init":     {},
	}
	for _, callback := range callbacks {
		reserved["invoke-"+callback.name] = struct{}{}
	}
	localNames := localTypeNames(used, reserved)

	fmt.Fprintln(output, "interface plugin {")
	renderUse(output, used, localNames)
	fmt.Fprintln(output)
	fmt.Fprintln(output, "  record plugin-metadata {")
	fmt.Fprintln(output, "    name: string,")
	fmt.Fprintln(output, "    version: string,")
	fmt.Fprintln(output, "    contract-hash: string,")
	fmt.Fprintln(output, "    generator-format: u32,")
	fmt.Fprintln(output, "  }")
	fmt.Fprintln(output)
	fmt.Fprintln(output, "  metadata: func() -> plugin-metadata;")
	fmt.Fprintf(
		output,
		"  init: func(context: borrow<%s>, proxy: borrow<%s>) -> result<_, gate-error>;\n",
		contextName,
		proxyName,
	)
	for _, callback := range callbacks {
		callable := callback.typ.Callback.Callable
		parameters := []string{"id: u64"}
		for _, parameter := range callable.Parameters {
			parameters = append(
				parameters,
				parameter.WITName+": "+
					registry.typeExpression(
						parameter.Type,
						witInput,
						localNames,
						"",
					),
			)
		}
		fmt.Fprintf(
			output,
			"  invoke-%s: func(%s)%s;\n",
			callback.name,
			strings.Join(parameters, ", "),
			registry.resultExpression(callable, localNames),
		)
	}
	fmt.Fprintln(output, "}")
}

func renderCallbacksInterface(output *bytes.Buffer, registry *witRegistry) {
	callbacks := registry.callbacks()
	used := map[string]struct{}{"gate-error": {}}
	reserved := make(map[string]struct{}, len(callbacks)*2)
	for _, callback := range callbacks {
		collectDefinitionUse(callback.identity, registry, used)
		for _, parameter := range callback.typ.Callback.Callable.Parameters {
			collectTypeUses(parameter.Type, registry, used)
		}
		for _, result := range callback.typ.Callback.Callable.Results {
			collectTypeUses(result.Type, registry, used)
		}
		reserved["new-"+callback.name] = struct{}{}
		reserved["call-"+callback.name] = struct{}{}
	}
	localNames := localTypeNames(used, reserved)

	fmt.Fprintln(output, "interface gate-callbacks {")
	renderUse(output, used, localNames)
	if len(used) > 0 && len(callbacks) > 0 {
		fmt.Fprintln(output)
	}
	for _, callback := range callbacks {
		callbackType := callback.typ
		callbackType.Nullable = false
		callbackType.Ownership = model.OwnershipOwn
		fmt.Fprintf(
			output,
			"  new-%s: func(id: u64) -> %s;\n",
			callback.name,
			registry.typeExpression(callbackType, witOutput, localNames, ""),
		)

		callbackType.Ownership = model.OwnershipBorrow
		parameters := []string{
			"callback: " +
				registry.typeExpression(callbackType, witInput, localNames, ""),
		}
		callable := callback.typ.Callback.Callable
		for _, parameter := range callable.Parameters {
			parameters = append(
				parameters,
				parameter.WITName+": "+
					registry.typeExpression(
						parameter.Type,
						witInput,
						localNames,
						"",
					),
			)
		}
		fmt.Fprintf(
			output,
			"  call-%s: func(%s)%s;\n",
			callback.name,
			strings.Join(parameters, ", "),
			registry.resultExpression(callable, localNames),
		)
	}
	fmt.Fprintln(output, "}")
}

func (r *witRegistry) callbacks() []*witDefinition {
	var callbacks []*witDefinition
	for _, definition := range r.definitions {
		if definition.typ.Kind == model.TypeCallback &&
			definition.typ.Callback != nil {
			callbacks = append(callbacks, definition)
		}
	}
	slices.SortFunc(callbacks, func(left, right *witDefinition) int {
		return strings.Compare(left.name, right.name)
	})
	return callbacks
}

func renderUse(
	output *bytes.Buffer,
	used map[string]struct{},
	localNames map[string]string,
) {
	var names []string
	for identity := range used {
		if identity == "gate-error" {
			names = append(names, renderUseName("gate-error", localNames))
			continue
		}
		// The caller has already collected canonical identities; the registry
		// name is injected by collect helpers as a "name:" pseudo identity.
		if strings.HasPrefix(identity, "name:") {
			names = append(
				names,
				renderUseName(strings.TrimPrefix(identity, "name:"), localNames),
			)
		}
	}
	slices.Sort(names)
	names = slices.Compact(names)
	if len(names) > 0 {
		fmt.Fprintf(output, "  use gate-types.{%s};\n", strings.Join(names, ", "))
	}
}

func renderUseName(name string, localNames map[string]string) string {
	if local := localNames[name]; local != "" && local != name {
		return name + " as " + local
	}
	return name
}

func operationNames(declarations []model.Declaration) map[string]struct{} {
	names := make(map[string]struct{}, len(declarations))
	for _, declaration := range declarations {
		switch declaration.Kind {
		case model.DeclarationConstant:
			names["get-"+declaration.WITName] = struct{}{}
		case model.DeclarationVariable:
			names["get-"+declaration.WITName] = struct{}{}
			if declaration.Variable != nil && declaration.Variable.Writable {
				names["set-"+declaration.WITName] = struct{}{}
			}
		default:
			names[declaration.WITName] = struct{}{}
		}
	}
	return names
}

func localTypeNames(
	used map[string]struct{},
	reserved map[string]struct{},
) map[string]string {
	names := make(map[string]string)
	occupied := make(map[string]struct{}, len(reserved)+len(used))
	for name := range reserved {
		occupied[name] = struct{}{}
	}
	var imported []string
	for identity := range used {
		switch {
		case identity == "gate-error":
			imported = append(imported, identity)
		case strings.HasPrefix(identity, "name:"):
			imported = append(imported, strings.TrimPrefix(identity, "name:"))
		}
	}
	slices.Sort(imported)
	imported = slices.Compact(imported)
	for _, name := range imported {
		local := name
		if _, collision := occupied[local]; collision {
			local = "type-" + name
			if _, collision := occupied[local]; collision {
				local += "-" + shortHash(name)
			}
		}
		names[name] = local
		occupied[local] = struct{}{}
	}
	return names
}

func collectDeclarationUses(
	declaration model.Declaration,
	registry *witRegistry,
	used map[string]struct{},
) {
	if declaration.Receiver != nil {
		identity := declaration.Receiver.TypeIdentity
		if declaration.Receiver.Pointer {
			if definition := registry.definitions[identity]; definition != nil &&
				definition.typ.Kind != model.TypeResource {
				identity += "#pointer"
			}
		}
		collectDefinitionUse(identity, registry, used)
	}
	if declaration.Type != nil {
		collectTypeUses(*declaration.Type, registry, used)
	}
	if declaration.Callable != nil {
		for _, parameter := range declaration.Callable.Parameters {
			collectTypeUses(parameter.Type, registry, used)
		}
		for _, result := range declaration.Callable.Results {
			collectTypeUses(result.Type, registry, used)
		}
		if declaration.Callable.Error != nil {
			used["gate-error"] = struct{}{}
		}
	}
}

func collectTypeUses(
	typ model.Type,
	registry *witRegistry,
	used map[string]struct{},
) {
	if needsWITDefinition(typ) {
		collectDefinitionUse(witTypeIdentity(typ), registry, used)
	}
	if typ.Element != nil {
		collectTypeUses(*typ.Element, registry, used)
	}
	if typ.Key != nil {
		collectTypeUses(*typ.Key, registry, used)
	}
	for _, field := range typ.Fields {
		collectTypeUses(field.Type, registry, used)
	}
	for _, variant := range typ.Cases {
		if variant.Type != nil {
			collectTypeUses(*variant.Type, registry, used)
		}
	}
	for _, tuple := range typ.Tuple {
		collectTypeUses(tuple, registry, used)
	}
}

func collectDefinitionUse(
	identity string,
	registry *witRegistry,
	used map[string]struct{},
) {
	if definition := registry.definitions[identity]; definition != nil {
		used["name:"+definition.name] = struct{}{}
	}
}

func (r *witRegistry) typeExpression(
	typ model.Type,
	position witPosition,
	localNames map[string]string,
	skipIdentity string,
) string {
	var expression string
	identity := witTypeIdentity(typ)
	if identity != "" && identity != skipIdentity {
		if definition := r.definitions[identity]; definition != nil {
			expression = definition.name
			if local := localNames[definition.name]; local != "" {
				expression = local
			}
			if typ.Kind == model.TypeResource ||
				typ.Kind == model.TypeCallback ||
				typ.Kind == model.TypeDynamic {
				switch position {
				case witInput:
					if typ.Ownership == model.OwnershipOwn {
						expression = "own<" + expression + ">"
					} else {
						expression = "borrow<" + expression + ">"
					}
				default:
					expression = "own<" + expression + ">"
				}
			}
		}
	}
	if expression == "" {
		switch typ.Kind {
		case model.TypeBool:
			expression = "bool"
		case model.TypeS8:
			expression = "s8"
		case model.TypeS16:
			expression = "s16"
		case model.TypeS32:
			expression = "s32"
		case model.TypeS64:
			expression = "s64"
		case model.TypeU8:
			expression = "u8"
		case model.TypeU16:
			expression = "u16"
		case model.TypeU32:
			expression = "u32"
		case model.TypeU64:
			expression = "u64"
		case model.TypeF32:
			expression = "f32"
		case model.TypeF64:
			expression = "f64"
		case model.TypeChar:
			expression = "char"
		case model.TypeString:
			expression = "string"
		case model.TypeList:
			expression = "list<" +
				r.typeExpression(*typ.Element, witNested, localNames, "") + ">"
		case model.TypeTuple:
			items := make([]string, len(typ.Tuple))
			for index, item := range typ.Tuple {
				items[index] = r.typeExpression(item, witNested, localNames, "")
			}
			expression = "tuple<" + strings.Join(items, ", ") + ">"
		case model.TypeOption:
			expression = "option<" +
				r.typeExpression(*typ.Element, witNested, localNames, "") + ">"
		case model.TypeResult:
			okType := "_"
			errorType := "_"
			if typ.Element != nil {
				okType = r.typeExpression(*typ.Element, witNested, localNames, "")
			}
			if typ.Key != nil {
				errorType = r.typeExpression(*typ.Key, witNested, localNames, "")
			}
			expression = "result<" + okType + ", " + errorType + ">"
		default:
			if definition := r.definitions[identity]; definition != nil {
				expression = definition.name
			} else {
				panic("missing WIT definition for " + identity)
			}
		}
	}
	if typ.Nullable {
		expression = "option<" + expression + ">"
	}
	return expression
}

func needsWITDefinition(typ model.Type) bool {
	if typ.Identity != "" {
		return true
	}
	switch typ.Kind {
	case model.TypeRecord, model.TypeVariant, model.TypeEnum, model.TypeFlags,
		model.TypeResource, model.TypeCallback, model.TypeDynamic:
		return true
	default:
		return false
	}
}

func witTypeIdentity(typ model.Type) string {
	if typ.Identity != "" {
		return typ.Identity
	}
	if !needsWITDefinition(typ) {
		return ""
	}
	encoded, err := json.Marshal(typ)
	if err != nil {
		panic(err)
	}
	sum := sha256.Sum256(encoded)
	return "anonymous-" + string(typ.Kind) + "-" + fmt.Sprintf("%x", sum[:8])
}

func preferredTypeNameFor(typ model.Type, identity string) string {
	if typ.WITName != "" {
		return typ.WITName
	}
	return preferredTypeName(identity)
}

func preferredTypeName(identity string) string {
	short := identity
	if dot := strings.LastIndexByte(short, '.'); dot >= 0 {
		short = short[dot+1:]
	}
	short = strings.ReplaceAll(short, "#pointer", "-pointer")
	if bracket := strings.IndexByte(short, '['); bracket >= 0 {
		short = short[:bracket] + "-" + shortHash(identity)
	}
	short = strings.ToLower(strings.ReplaceAll(short, "_", "-"))
	if strings.HasPrefix(short, "anonymous-") {
		return short
	}
	if short == "" {
		return "anonymous-" + shortHash(identity)
	}
	return short
}

func shortHash(identity string) string {
	sum := sha256.Sum256([]byte(identity))
	return fmt.Sprintf("%x", sum[:6])
}

func renderDocumentation(output *bytes.Buffer, indent, documentation string) {
	for _, line := range strings.Split(strings.TrimSpace(documentation), "\n") {
		if line != "" {
			fmt.Fprintf(output, "%s/// %s\n", indent, line)
		}
	}
}
