package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"

	"go.minekube.com/gate/internal/builtin/wasm/codegen/model"
)

const callbackOperationBase uint32 = 1 << 31

type generatedCallback struct {
	ID              uint32
	Identity        string
	WITName         string
	CallOperationID uint32
}

func generatedCallbacks(api *model.API) ([]generatedCallback, error) {
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	registry, err := newWITRegistry(normalized)
	if err != nil {
		return nil, err
	}
	definitions := registry.callbacks()
	callbacks := make([]generatedCallback, len(definitions))
	for index, definition := range definitions {
		id := uint32(index + 1)
		callbacks[index] = generatedCallback{
			ID:              id,
			Identity:        definition.identity,
			WITName:         definition.name,
			CallOperationID: callbackOperationBase | id,
		}
	}
	return callbacks, nil
}

// RenderGoCallbacks renders the synchronized callback descriptors and
// host-returned callback invocation dispatchers.
func RenderGoCallbacks(api *model.API) ([]byte, error) {
	callbacks, err := generatedCallbacks(api)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by gate-wasm-gen; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package api")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "import (")
	fmt.Fprintln(&output, "\t\"context\"")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"\t\"go.minekube.com/gate/internal/builtin/wasm/runtime/dispatch\"",
	)
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type GeneratedCallbackDescriptor struct {")
	fmt.Fprintln(&output, "\tID uint32")
	fmt.Fprintln(&output, "\tIdentity string")
	fmt.Fprintln(&output, "\tWITName string")
	fmt.Fprintln(&output, "\tCallOperationID uint32")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"var GeneratedCallbacks = [...]GeneratedCallbackDescriptor{",
	)
	for _, callback := range callbacks {
		fmt.Fprintln(&output, "\t{")
		fmt.Fprintf(&output, "\t\tID: %d,\n", callback.ID)
		fmt.Fprintf(
			&output,
			"\t\tIdentity: %s,\n",
			strconv.Quote(callback.Identity),
		)
		fmt.Fprintf(
			&output,
			"\t\tWITName: %s,\n",
			strconv.Quote(callback.WITName),
		)
		fmt.Fprintf(
			&output,
			"\t\tCallOperationID: %d,\n",
			callback.CallOperationID,
		)
		fmt.Fprintln(&output, "\t},")
	}
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"func RegisterGeneratedCallbacks(host *dispatch.Host) error {",
	)
	for index, callback := range callbacks {
		fmt.Fprintln(&output, "\tif err := host.Register(dispatch.Operation{")
		fmt.Fprintf(
			&output,
			"\t\tID: %d,\n",
			callback.CallOperationID,
		)
		fmt.Fprintf(
			&output,
			"\t\tIdentity: %s,\n",
			strconv.Quote(callback.Identity+"#call"),
		)
		fmt.Fprintf(
			&output,
			"\t\tHandler: generatedCallbackDispatch%04d,\n",
			index+1,
		)
		fmt.Fprintln(&output, "\t}); err != nil {")
		fmt.Fprintln(&output, "\t\treturn err")
		fmt.Fprintln(&output, "\t}")
	}
	fmt.Fprintln(&output, "\treturn nil")
	fmt.Fprintln(&output, "}")
	for index, callback := range callbacks {
		fmt.Fprintln(&output)
		fmt.Fprintf(
			&output,
			"func generatedCallbackDispatch%04d(ctx context.Context, host *dispatch.Host, arguments []any) ([]any, error) {\n",
			index+1,
		)
		fmt.Fprintln(&output, "\treturn host.CallResource(ctx, dispatch.Operation{")
		fmt.Fprintf(
			&output,
			"\t\tID: %d,\n",
			callback.CallOperationID,
		)
		fmt.Fprintf(
			&output,
			"\t\tIdentity: %s,\n",
			strconv.Quote(callback.Identity+"#call"),
		)
		fmt.Fprintln(&output, "\t}, arguments)")
		fmt.Fprintln(&output, "}")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go callbacks: %w", err)
	}
	return formatted, nil
}
