package generate

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"

	"go.minekube.com/gate/internal/builtin/wasm/codegen/model"
)

func RenderRustBindings(api *model.API) ([]byte, error) {
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by gate-wasm-gen; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"pub const GENERATOR_FORMAT: u32 = %d;\n",
		normalized.FormatVersion,
	)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "wasmtime::component::bindgen!({")
	fmt.Fprintln(&output, "    path: \"../../../api\",")
	fmt.Fprintln(&output, "    world: \"gate-plugin\",")
	fmt.Fprintln(&output, "    imports: { default: trappable | store },")
	fmt.Fprintln(&output, "});")
	return output.Bytes(), nil
}

func RenderRustDispatch(api *model.API) ([]byte, error) {
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	operations, err := Operations(normalized)
	if err != nil {
		return nil, err
	}
	witHash, err := generatedWITHash(normalized)
	if err != nil {
		return nil, err
	}
	wit, err := RenderWIT(normalized)
	if err != nil {
		return nil, err
	}
	resources := generatedWITResources(wit)
	registry, err := newWITRegistry(normalized)
	if err != nil {
		return nil, err
	}
	callbacks := registry.callbacks()
	resourceIDs := make(map[string]int, len(resources))
	for index, resource := range resources {
		resourceIDs[resource] = index + 1
	}
	packages := make(map[string]string, len(normalized.Packages))
	for _, pkg := range normalized.Packages {
		packages[pkg.Path] = pkg.WITName
	}
	declarations := make(
		map[string]model.Declaration,
		len(normalized.Declarations),
	)
	for _, declaration := range normalized.Declarations {
		declarations[declaration.Identity] = declaration
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by gate-wasm-gen; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"use wasmtime::StoreContextMut;",
	)
	fmt.Fprintln(
		&output,
		"use wasmtime::component::{Linker, ResourceType, Val, types::ComponentFunc};",
	)
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"pub const WIT_HASH: &str = %s;\n",
		strconv.Quote(witHash),
	)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
	fmt.Fprintln(&output, "pub struct Operation {")
	fmt.Fprintln(&output, "    pub id: u32,")
	fmt.Fprintln(&output, "    pub identity: &'static str,")
	fmt.Fprintln(&output, "    pub interface: &'static str,")
	fmt.Fprintln(&output, "    pub name: &'static str,")
	fmt.Fprintln(&output, "    pub kind: &'static str,")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "pub static OPERATIONS: &[Operation] = &[")
	for _, operation := range operations {
		declaration := declarations[operation.DeclarationIdentity]
		fmt.Fprintln(&output, "    Operation {")
		fmt.Fprintf(&output, "        id: %d,\n", operation.ID)
		fmt.Fprintf(
			&output,
			"        identity: %s,\n",
			strconv.Quote(operation.Identity),
		)
		fmt.Fprintf(
			&output,
			"        interface: %s,\n",
			strconv.Quote(packages[declaration.PackagePath]),
		)
		fmt.Fprintf(
			&output,
			"        name: %s,\n",
			strconv.Quote(operation.WITName),
		)
		fmt.Fprintf(
			&output,
			"        kind: %s,\n",
			strconv.Quote(string(operation.Kind)),
		)
		fmt.Fprintln(&output, "    },")
	}
	fmt.Fprintln(&output, "];")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
	fmt.Fprintln(&output, "pub struct CallbackDescriptor {")
	fmt.Fprintln(&output, "    pub id: u32,")
	fmt.Fprintln(&output, "    pub type_id: u32,")
	fmt.Fprintln(&output, "    pub identity: &'static str,")
	fmt.Fprintln(&output, "    pub name: &'static str,")
	fmt.Fprintln(&output, "    pub new_name: &'static str,")
	fmt.Fprintln(&output, "    pub call_name: &'static str,")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"pub static CALLBACKS: &[CallbackDescriptor] = &[",
	)
	for index, callback := range callbacks {
		fmt.Fprintln(&output, "    CallbackDescriptor {")
		fmt.Fprintf(&output, "        id: %d,\n", index+1)
		fmt.Fprintf(
			&output,
			"        type_id: %d,\n",
			resourceIDs[callback.name],
		)
		fmt.Fprintf(
			&output,
			"        identity: %s,\n",
			strconv.Quote(callback.identity),
		)
		fmt.Fprintf(&output, "        name: %s,\n", strconv.Quote(callback.name))
		fmt.Fprintf(
			&output,
			"        new_name: %s,\n",
			strconv.Quote("new-"+callback.name),
		)
		fmt.Fprintf(
			&output,
			"        call_name: %s,\n",
			strconv.Quote("call-"+callback.name),
		)
		fmt.Fprintln(&output, "    },")
	}
	fmt.Fprintln(&output, "];")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
	fmt.Fprintln(&output, "pub struct ResourceDescriptor {")
	fmt.Fprintln(&output, "    pub id: u32,")
	fmt.Fprintln(&output, "    pub name: &'static str,")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"pub static RESOURCE_TYPES: &[ResourceDescriptor] = &[",
	)
	for index, resource := range resources {
		fmt.Fprintln(&output, "    ResourceDescriptor {")
		fmt.Fprintf(&output, "        id: %d,\n", index+1)
		fmt.Fprintf(&output, "        name: %s,\n", strconv.Quote(resource))
		fmt.Fprintln(&output, "    },")
	}
	fmt.Fprintln(&output, "];")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "pub trait Dispatch: Sized + 'static {")
	fmt.Fprintln(&output, "    fn invoke(")
	fmt.Fprintln(&output, "        store: StoreContextMut<'_, Self>,")
	fmt.Fprintln(&output, "        operation: &'static Operation,")
	fmt.Fprintln(&output, "        function_type: ComponentFunc,")
	fmt.Fprintln(&output, "        parameters: &[Val],")
	fmt.Fprintln(&output, "        results: &mut [Val],")
	fmt.Fprintln(&output, "    ) -> wasmtime::Result<()>;")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "    fn register_callback(")
	fmt.Fprintln(&output, "        store: StoreContextMut<'_, Self>,")
	fmt.Fprintln(&output, "        callback: &'static CallbackDescriptor,")
	fmt.Fprintln(&output, "        guest_id: u64,")
	fmt.Fprintln(&output, "        results: &mut [Val],")
	fmt.Fprintln(&output, "    ) -> wasmtime::Result<()>;")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "    fn call_callback(")
	fmt.Fprintln(&output, "        store: StoreContextMut<'_, Self>,")
	fmt.Fprintln(&output, "        callback: &'static CallbackDescriptor,")
	fmt.Fprintln(&output, "        function_type: ComponentFunc,")
	fmt.Fprintln(&output, "        parameters: &[Val],")
	fmt.Fprintln(&output, "        results: &mut [Val],")
	fmt.Fprintln(&output, "    ) -> wasmtime::Result<()>;")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "    fn drop_resource(")
	fmt.Fprintln(&output, "        store: StoreContextMut<'_, Self>,")
	fmt.Fprintln(&output, "        resource: &'static ResourceDescriptor,")
	fmt.Fprintln(&output, "        representation: u32,")
	fmt.Fprintln(&output, "    ) -> wasmtime::Result<()>;")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"pub fn add_to_linker<T: Dispatch>(linker: &mut Linker<T>) -> wasmtime::Result<()> {",
	)
	fmt.Fprintln(&output, "    {")
	fmt.Fprintln(
		&output,
		"        let mut instance = linker.instance(\"minekube:gate/gate-types@0.1.0\")?;",
	)
	for index := range resources {
		fmt.Fprintf(&output, "        let resource = &RESOURCE_TYPES[%d];\n", index)
		fmt.Fprintln(&output, "        instance.resource(")
		fmt.Fprintln(&output, "            resource.name,")
		fmt.Fprintln(
			&output,
			"            ResourceType::host_dynamic(resource.id),",
		)
		fmt.Fprintln(
			&output,
			"            move |store, representation| T::drop_resource(store, resource, representation),",
		)
		fmt.Fprintln(&output, "        )?;")
	}
	fmt.Fprintln(&output, "    }")
	operationIndex := 0
	for _, pkg := range normalized.Packages {
		var packageOperations []GeneratedOperation
		for operationIndex < len(operations) {
			operation := operations[operationIndex]
			declaration := declarations[operation.DeclarationIdentity]
			if declaration.PackagePath < pkg.Path {
				operationIndex++
				continue
			}
			if declaration.PackagePath != pkg.Path {
				break
			}
			packageOperations = append(packageOperations, operation)
			operationIndex++
		}
		if len(packageOperations) == 0 {
			continue
		}
		fmt.Fprintln(&output, "    {")
		interfaceLine := fmt.Sprintf(
			"        let interface_name = concat!(\"minekube:gate/\", %s, \"@0.1.0\",);",
			strconv.Quote(pkg.WITName),
		)
		if len(interfaceLine) <= 100 {
			fmt.Fprintln(&output, interfaceLine)
		} else {
			fmt.Fprintln(&output, "        let interface_name = concat!(")
			fmt.Fprintln(&output, "            \"minekube:gate/\",")
			fmt.Fprintf(&output, "            %s,\n", strconv.Quote(pkg.WITName))
			fmt.Fprintln(&output, "            \"@0.1.0\",")
			fmt.Fprintln(&output, "        );")
		}
		fmt.Fprintln(
			&output,
			"        let mut instance = linker.instance(interface_name)?;",
		)
		for _, operation := range packageOperations {
			fmt.Fprintf(
				&output,
				"        let operation = &OPERATIONS[%d];\n",
				operation.ID-1,
			)
			fmt.Fprintln(&output, "        instance.func_new(")
			fmt.Fprintln(&output, "            operation.name,")
			fmt.Fprintln(
				&output,
				"            move |store, function_type, parameters, results| {",
			)
			fmt.Fprintln(
				&output,
				"                T::invoke(store, operation, function_type, parameters, results)",
			)
			fmt.Fprintln(&output, "            },")
			fmt.Fprintln(&output, "        )?;")
		}
		fmt.Fprintln(&output, "    }")
	}
	if len(callbacks) > 0 {
		fmt.Fprintln(&output, "    {")
		fmt.Fprintln(
			&output,
			"        let mut instance = linker.instance(\"minekube:gate/gate-callbacks@0.1.0\")?;",
		)
		for index := range callbacks {
			fmt.Fprintf(&output, "        let callback = &CALLBACKS[%d];\n", index)
			fmt.Fprintln(&output, "        instance.func_new(")
			fmt.Fprintln(&output, "            callback.new_name,")
			fmt.Fprintln(
				&output,
				"            move |store, _function_type, parameters, results| {",
			)
			fmt.Fprintln(&output, "                let [Val::U64(guest_id)] = parameters else {")
			fmt.Fprintln(
				&output,
				"                    return Err(wasmtime::Error::msg(",
			)
			fmt.Fprintln(
				&output,
				"                        \"callback constructor expected one u64 ID\",",
			)
			fmt.Fprintln(&output, "                    ));")
			fmt.Fprintln(&output, "                };")
			fmt.Fprintln(
				&output,
				"                T::register_callback(store, callback, *guest_id, results)",
			)
			fmt.Fprintln(&output, "            },")
			fmt.Fprintln(&output, "        )?;")
			fmt.Fprintln(&output, "        instance.func_new(")
			fmt.Fprintln(&output, "            callback.call_name,")
			fmt.Fprintln(
				&output,
				"            move |store, function_type, parameters, results| {",
			)
			fmt.Fprintln(
				&output,
				"                T::call_callback(store, callback, function_type, parameters, results)",
			)
			fmt.Fprintln(&output, "            },")
			fmt.Fprintln(&output, "        )?;")
		}
		fmt.Fprintln(&output, "    }")
	}
	fmt.Fprintln(&output, "    Ok(())")
	fmt.Fprintln(&output, "}")
	return output.Bytes(), nil
}

func RenderCHeader(api *model.API) ([]byte, error) {
	normalized, err := normalizedAPI(api)
	if err != nil {
		return nil, err
	}
	operations, err := Operations(normalized)
	if err != nil {
		return nil, err
	}
	abi, err := BuildABI(normalized)
	if err != nil {
		return nil, err
	}
	witHash, err := generatedWITHash(normalized)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "/* Code generated by gate-wasm-gen; DO NOT EDIT. */")
	fmt.Fprintln(&output, "#ifndef GATE_WASM_GENERATED_H")
	fmt.Fprintln(&output, "#define GATE_WASM_GENERATED_H")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "#include <stdint.h>")
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"#define GATE_WASM_GENERATOR_FORMAT %d\n",
		normalized.FormatVersion,
	)
	fmt.Fprintf(
		&output,
		"#define GATE_WASM_ABI_SCHEMA_VERSION %d\n",
		abi.Version,
	)
	fmt.Fprintf(
		&output,
		"#define GATE_WASM_OPERATION_COUNT %d\n",
		len(operations),
	)
	fmt.Fprintf(
		&output,
		"#define GATE_WASM_WIT_HASH %s\n",
		strconv.Quote(witHash),
	)
	fmt.Fprintf(
		&output,
		"#define GATE_WASM_ABI_LAYOUT_HASH %s\n",
		strconv.Quote(abi.Fingerprint),
	)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "typedef uint64_t gate_wasm_handle;")
	fmt.Fprintln(&output, "typedef uint32_t gate_wasm_discriminant;")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "typedef struct gate_wasm_borrowed_buffer {")
	fmt.Fprintln(&output, "  uint64_t pointer;")
	fmt.Fprintln(&output, "  uint64_t length;")
	fmt.Fprintln(&output, "} gate_wasm_borrowed_buffer;")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "typedef struct gate_wasm_owned_buffer {")
	fmt.Fprintln(&output, "  uint64_t pointer;")
	fmt.Fprintln(&output, "  uint64_t length;")
	fmt.Fprintln(&output, "  uint64_t capacity;")
	fmt.Fprintln(&output, "} gate_wasm_owned_buffer;")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "#endif")
	return output.Bytes(), nil
}

func generatedWITHash(api *model.API) (string, error) {
	wit, err := RenderWIT(api)
	if err != nil {
		return "", err
	}
	hash := sha256.Sum256(wit)
	return hex.EncodeToString(hash[:]), nil
}

func generatedWITResources(wit []byte) []string {
	var resources []string
	depth := 0
	for _, line := range bytes.Split(wit, []byte{'\n'}) {
		text := string(bytes.TrimSpace(line))
		if depth == 0 {
			if text == "interface gate-types {" {
				depth = 1
			}
			continue
		}
		if depth == 1 &&
			strings.HasPrefix(text, "resource ") &&
			strings.HasSuffix(text, ";") {
			resources = append(
				resources,
				strings.TrimSuffix(strings.TrimPrefix(text, "resource "), ";"),
			)
		}
		depth += strings.Count(text, "{")
		depth -= strings.Count(text, "}")
		if depth == 0 {
			return resources
		}
	}
	return resources
}
