package generate

import (
	"bytes"
	"fmt"
	"strconv"

	"go.minekube.com/gate/internal/builtin/wasm/codegen/model"
)

// RenderRustValues renders Rust descriptors from the exact same ABI schema as
// RenderGoValues.
func RenderRustValues(api *model.API) ([]byte, error) {
	schema, err := BuildABI(api)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by gate-wasm-gen; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintf(
		&output,
		"/// ABI schema version %d.\n",
		schema.Version,
	)
	fmt.Fprintf(
		&output,
		"pub const ABI_SCHEMA_VERSION: u32 = %d;\n",
		schema.Version,
	)
	fmt.Fprintf(
		&output,
		"pub const ABI_LAYOUT_FINGERPRINT: &str =\n    %s;\n",
		strconv.Quote(schema.Fingerprint),
	)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
	fmt.Fprintln(&output, "pub struct ValueLayout {")
	fmt.Fprintln(&output, "    pub identity: &'static str,")
	fmt.Fprintln(&output, "    pub direction: &'static str,")
	fmt.Fprintln(&output, "    pub kind: &'static str,")
	fmt.Fprintln(&output, "    pub size: u64,")
	fmt.Fprintln(&output, "    pub alignment: u32,")
	fmt.Fprintln(&output, "    pub allocator: &'static str,")
	fmt.Fprintln(&output, "    pub free_operation: &'static str,")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "pub static VALUE_LAYOUTS: &[ValueLayout] = &[")
	for _, entry := range schema.Layouts {
		fmt.Fprintln(&output, "    ValueLayout {")
		fmt.Fprintf(
			&output,
			"        identity: %s,\n",
			strconv.Quote(entry.Identity),
		)
		fmt.Fprintf(
			&output,
			"        direction: %s,\n",
			strconv.Quote(string(entry.Direction)),
		)
		fmt.Fprintf(
			&output,
			"        kind: %s,\n",
			strconv.Quote(string(entry.Layout.Kind)),
		)
		fmt.Fprintf(&output, "        size: %d,\n", entry.Layout.Size)
		fmt.Fprintf(
			&output,
			"        alignment: %d,\n",
			entry.Layout.Alignment,
		)
		fmt.Fprintf(
			&output,
			"        allocator: %s,\n",
			strconv.Quote(string(entry.Layout.Allocator)),
		)
		fmt.Fprintf(
			&output,
			"        free_operation: %s,\n",
			strconv.Quote(entry.Layout.FreeOperation),
		)
		fmt.Fprintln(&output, "    },")
	}
	fmt.Fprintln(&output, "];")
	fmt.Fprintln(&output)
	fmt.Fprintln(
		&output,
		"const _: [(); 8] = [(); core::mem::size_of::<u64>()];",
	)
	return output.Bytes(), nil
}
