package bedrockidentity

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// These are Moxy producer fixtures, not signatures generated by this verifier.
func TestMoxyV1Contract(t *testing.T) {
	var manifest struct {
		Key     string                                    `json:"public_key_base64"`
		Now     int64                                     `json:"verification_time_unix_ms"`
		Vectors []struct{ File, SHA256, Expected string } `json:"vectors"`
	}
	data, err := os.ReadFile("testdata/v1/manifest.json")
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(data, &manifest))
	key, err := base64.StdEncoding.DecodeString(manifest.Key)
	require.NoError(t, err)
	for _, vector := range manifest.Vectors {
		t.Run(vector.File, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join("testdata/v1", vector.File))
			require.NoError(t, err)
			hash := sha256.Sum256(data)
			require.Equal(t, vector.SHA256, hex.EncodeToString(hash[:]))
			if vector.Expected == "duplicate_property" {
				return
			} // proposal-level vector
			org := "org-id"
			if strings.Contains(vector.File, "orgless") {
				org = ""
			}
			opts := VerifyOptions{
				Public: ed25519.PublicKey(key), ExpectedIssuer: "minekube-connect",
				EndpointID: "endpoint-id", EndpointName: "fixture-endpoint", OrgID: org,
				SessionID: "session-id", Protocol: "bedrock", Replay: NewReplayCache(),
				Now: func() time.Time { return time.UnixMilli(manifest.Now) },
			}
			claims, err := Verify(string(data), opts)
			if strings.HasPrefix(vector.Expected, "valid_") {
				require.NoError(t, err)
				require.Equal(t, org, claims.OrgID)
				_, err = Verify(string(data), opts)
				require.ErrorContains(t, err, "replayed")
			} else {
				require.Error(t, err)
			}
		})
	}
}

func TestEnvelopeRejectsAmbiguousJSON(t *testing.T) {
	data, err := os.ReadFile("testdata/v1/v1-bedrock-xuid-valid.json")
	require.NoError(t, err)
	for _, bad := range []string{
		strings.Replace(string(data), `"version":1`, `"version":1,"version":1`, 1),
		strings.Replace(string(data), `"org_id":"org-id"`, `"org_id":null`, 1),
		strings.Replace(string(data), `,"org_id":"org-id"`, ``, 1),
		string(data) + `{}`, strings.Repeat("x", MaxEnvelopeBytes+1),
	} {
		_, err := decodeEnvelope(bad)
		require.Error(t, err)
	}
}

func TestReplayCapacityFailsClosedAndExpires(t *testing.T) {
	c := NewReplayCache()
	for i := range MaxReplayEntries {
		require.True(t, c.accept(string(rune(i)), 1, 10))
	}
	require.False(t, c.accept("overflow", 1, 10))
	require.True(t, c.accept("after-expiry", 10, 20))
}
